image:
  repository: microsoft/virtual-kubelet
  tag: latest
  pullPolicy: Always

## `provider` should be one of aws, azure, azurebatch, etc...
provider: 
nodeName: "virtual-kubelet"
nodeTaint: "azure.com/aci"
nodeOsType: "Linux"
monitoredNamespace: ""
apiserverCert: 
apiserverKey: 

providers:
  azure:
    ## Set to true if deploying to Azure Kubernetes Service (AKS), otherwise false
    targetAKS: true
    clientId: 
    clientKey: 
    tenantId: 
    subscriptionId: 
    aciResourceGroup: 
    aciRegion: "westus"
    loganalytics:
      enabled: false
      workspaceID: 
      workspaceKey: 

## Install Default RBAC roles and bindings
rbac:
  install: false
  serviceAccountName: virtual-kubelet
  ## RBAC api version
  apiVersion: v1beta1
  ## Cluster role reference
  roleRef: cluster-admin
