image:
  repository: microsoft/virtual-kubelet
  tag: latest
  pullPolicy: Always

nodeName: "virtual-kubelet"
nodeOsType: "Linux"
monitoredNamespace: ""
apiserverCert: 
apiserverKey: 
logLevel: 

taint:
  enabled: true
  key: virtual-kubelet.io/provider
  value: "{{ .Values.provider }}"
  ## `effect` must be `NoSchedule`, `PreferNoSchedule` or `NoExecute`.
  effect: NoSchedule

trace:
  exporter: ""
  serviceName: "{{ .Values.nodeName }}"
  sampleRate: 0

traceExporters:
  jaeger:
    name: "{{ .Values.trace.exporter }}"
    endpoint: ""
    image:
      repository: jaegertracing/all-in-one
      tag: 1.8
      pullPolicy: Always

providers:
  azure:
    ## Set to true if deploying to Azure Kubernetes Service (AKS), otherwise false
    targetAKS: true
    clientId: 
    clientKey: 
    tenantId: 
    subscriptionId: 
    ## `aciResourceGroup` and `aciRegion` are required only for non-AKS deployments
    aciResourceGroup: 
    aciRegion: 
    masterUri: 
    loganalytics:
      enabled: false
      workspaceId: 
      workspaceKey: 
      clusterResourceId: 
    vnet:
      enabled: false
      subnetName: 
      subnetCidr: 
      clusterCidr: 
      kubeDnsIp: 
  cri:
    implementation: containerd

criImplementations:
  containerd:
    image:
      pullPolicy: Always
      repository: cpuguy83/containerd
      tag: v1.2.5

cniConfig:
  - name: "99-localhost.conf"
    data: |-
      {
        "cniVersion": "0.2.0",
        "name": "lo",
        "type": "loopback"
      }

## Install Default RBAC roles and bindings
rbac:
  install: true
  serviceAccountName: virtual-kubelet
  ## RBAC api version
  apiVersion: v1beta1
  ## Cluster role reference
  roleRef: cluster-admin
