apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KUBELET_PORT
          value: "10250"
        - name: ACS_CREDENTIAL_LOCATION
          value: /etc/acs/azure.json
        - name: AZURE_TENANT_ID
          value: {{ .Values.env.azureTenantId }}
        - name: AZURE_SUBSCRIPTION_ID
          value: {{ .Values.env.azureSubscriptionId }}
        - name: AZURE_CLIENT_ID
          value: {{ .Values.env.azureClientId }}
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: clientSecret
        - name: ACI_RESOURCE_GROUP
          value: {{ .Values.env.aciResourceGroup }}
        - name: ACI_REGION
          value: {{ default "westus" .Values.env.aciRegion }}
        - name: APISERVER_CERT_LOCATION
          value: /etc/virtual-kubelet/cert.pem
        - name: APISERVER_KEY_LOCATION
          value: /etc/virtual-kubelet/key.pem
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ACI_EXTRA_USER_AGENT
          value: {{ printf "helm-chart/aks/%s/%s" .Chart.Name .Chart.Version }}
        - name: ACI_SUBNET_NAME
          value: {{ .Values.env.aciVnetSubnetName }}
        - name: ACI_SUBNET_CIDR
          value: {{ .Values.env.aciVnetSubnetCIDR }}
        - name: MASTER_URI
          value: {{ .Values.env.masterUri }}
        - name: CLUSTER_CIDR
          value: {{ .Values.env.clusterCIDR }}
        - name: KUBE_DNS_IP
          value: {{ .Values.env.kubeDnsIP }}
        {{ if .Values.loganalytics.enabled }}
        - name: LOG_ANALYTICS_AUTH_LOCATION
          value: /etc/virtual-kubelet/loganalytics.json
        {{ end }}
        volumeMounts:
        - name: credentials
          mountPath: "/etc/virtual-kubelet"
        - name: acs-credential
          mountPath: "/etc/acs/azure.json"
        command: ["virtual-kubelet"]
        args: ["--provider", "azure", "--namespace", {{ default "" .Values.env.monitoredNamespace | quote }}, "--nodename", {{ default "virtual-kubelet" .Values.env.nodeName | quote }} , "--os", {{ default "Linux" .Values.env.nodeOsType | quote }} ]
      volumes:
      - name: credentials
        secret:
          secretName: {{ template "fullname" . }}
      - name: acs-credential
        hostPath:
          path: /etc/kubernetes/azure.json
          type: File
      {{ if .Values.rbac.install }}
      serviceAccountName: {{ template "fullname" . }}
      {{ end }}
      nodeSelector:
        beta.kubernetes.io/os: linux